// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY81jAOsNuIx_6kfkIIQNwgqjencVH9qQ',
    appId: '1:827693478753:web:037060db44391e32290b20',
    messagingSenderId: '827693478753',
    projectId: 'todo-app-2109a',
    authDomain: 'todo-app-2109a.firebaseapp.com',
    storageBucket: 'todo-app-2109a.firebasestorage.app',
    measurementId: 'G-MTNTVD6EJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD93VeSKjRcSX0zcYW9EtZqRHJNMUsnJG0',
    appId: '1:827693478753:android:53c29eebce4728f3290b20',
    messagingSenderId: '827693478753',
    projectId: 'todo-app-2109a',
    storageBucket: 'todo-app-2109a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOqyeOIEQD8lL4VIRk0hKJoh1gTNetn0',
    appId: '1:827693478753:ios:6a2d80e95d219cea290b20',
    messagingSenderId: '827693478753',
    projectId: 'todo-app-2109a',
    storageBucket: 'todo-app-2109a.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
